
CREATE TABLE M_NOTIFICATIONS (
    OPERATION_CD VARCHAR(12) PRIMARY KEY NOT NULL, -- 業務コード
    USER_CD VARCHAR(8) NOT NULL, -- ユーザコード
    VALID_FLG CHAR(1) NOT NULL, -- 有効フラグ
    TO_FLG CHAR(1) NOT NULL, -- 宛先フラグ
    CC_FLG CHAR(1) NOT NULL, -- CCフラグ
    BCC_FLG CHAR(1) NOT NULL, -- BCCフラグ
    FROM_FLG CHAR(1) NOT NULL, -- 送信元フラグ
    created_timestamp TIMESTAMP, -- 登録日時
    created_by VARCHAR(12), -- 登録者コード
    updated_timestamp TIMESTAMP, -- 更新日時
    updated_by VARCHAR(12) -- 更新者コード
);

COMMENT ON COLUMN M_NOTIFICATIONS.OPERATION_CD IS '業務コード。担当者のみ内容変更可';
COMMENT ON COLUMN M_NOTIFICATIONS.USER_CD IS 'ユーザコード';
COMMENT ON COLUMN M_NOTIFICATIONS.VALID_FLG IS '有効フラグ';
COMMENT ON COLUMN M_NOTIFICATIONS.TO_FLG IS '宛先フラグ';
COMMENT ON COLUMN M_NOTIFICATIONS.CC_FLG IS 'CCフラグ';
COMMENT ON COLUMN M_NOTIFICATIONS.BCC_FLG IS 'BCCフラグ';
COMMENT ON COLUMN M_NOTIFICATIONS.FROM_FLG IS '送信元フラグ。有効の場合、自動でBCCに割り当て？';
COMMENT ON COLUMN M_NOTIFICATIONS.created_timestamp IS '登録日時';
COMMENT ON COLUMN M_NOTIFICATIONS.created_by IS '登録者コード';
COMMENT ON COLUMN M_NOTIFICATIONS.updated_timestamp IS '更新日時';
-- comment
